### PR TITLE
grab readme/image, new sample frontend

### PR DESCRIPTION
**Pull request by ngokevin**

### CODE REVIEW

**Comment by fernandojsg** [comment]
Maybe add one attribute on `registry.yml` to specify the `img` and just use this grab method in case it's not defined?

**Comment by ngokevin** [comment]
OK, I added a way to explicitly define an `image`. Ideally, they also live in the npm/GitHub to improve discoverability. If people visit a component page with no image on npm/GitHub, then they're less likely to engage with it because don't know what it looks like.

**Comment by ngokevin** [comment]
Sample frontend:

screen shot 2016-10-03 at 3 44 18 pm

screen shot 2016-10-03 at 3 44 12 pm

**Comment by fernandojsg** [comment]
Cool!

**Pull request merged**
