### PR TITLE
Register aframe-alongpath-component

### PR DESCRIPTION
**Pull request by protyze**
Added the aframe-alongpath-component to the A-Frame Registry by editing registry.yml

### CODE REVIEW

**Comment by ngokevin** [comment]
Thanks! Currently looking at Inspector-ready components, ideally there'd be a way to edit the points visually (i.e., add child entities and be able to drag those around to define the points).

**Comment by protyze** [comment]
Huh, that totally makes sense. Missed that one. I will extend the component as suggested. Thanks!

**Comment by protyze** [comment]
Hi, I've updated the component with A-Frame Inspector support. See https://protyze.github.io/aframe-alongpath-component/alongpath/index.html 

(Open the Inspector, select the red path-boxes and then drag the curve into position).

**Comment by ngokevin** [comment]
Looks great! Is there a way to clean up the scene graph a bit? Like put all those boxes under an entity, and give the wrapping entity a class name (we will show the class name in the Inspector soon).

screen shot 2016-10-21 at 3 38 11 pm

**Comment by ngokevin** [comment]
If we just make `inspect: false` and just add a bit to the README about that, then good to go! The scene graph clean up not a deal breaker.

**Comment by protyze** [comment]
Thank you for your feedback. I appreciate! All the inspector-entities are now cleaned up as child-elements of the ".alongpath-debug-root"-entity. Also I made some minor tweaks and updated the the inspector-Property to be false by default and described the inspector-usage in more detail in the readme. let me know if that's ok now, or if it needs some more work.

**Comment by ngokevin** [comment]
Awesome!

**Comment by ngokevin** [comment]
Could also be able to dynamically update the `closed` property, and perhaps use spheres instead of boxes.

**Comment by fernandojsg** [comment]
Supercool, first community component! thank you @protyze  :)

**Comment by protyze** [comment]
Cool! Thanks! I will also consider the other inputs. :)

**Pull request merged**
