### PR TITLE
add aframe-point-component

### PR DESCRIPTION
**Pull request by naugtur**
https://www.npmjs.com/package/aframe-point-component

### CODE REVIEW

**Comment by naugtur** [comment]
I'm not responsible for the failed tests, I just modified a yml file ;)

**Comment by ngokevin** [comment]
https://github.com/naugtur/aframe-point-component/issues/1

**Comment by naugtur** [comment]
done

**Comment by naugtur** [comment]
bump

**Comment by ngokevin** [comment]
You can use this image in your README instead and publish that to npm. If you want, you can add me as a collaborator on GitHub / npm to help maintain and I can polish some README stuff and tiny maintenance.

stars

**Comment by naugtur** [comment]
I didn't expect a gif is mandatory for getting accepted into registry :P 
I can get down to adding it after the weekend.

I've added you as a collaborator, the more the merrier!

**Comment by ngokevin** [comment]
It's not mandatory for a GIF, but since it's going to be the main image displayed on the Registry, it looks better than a few squares:

screen shot 2017-03-17 at 2 43 50 pm

**Comment by ngokevin** [comment]
I'll also need npm ownership + GitHub admin settings to do help polish (e.g., update the GIF, publish GitHub pages).

**Comment by naugtur** [comment]
Honestly, this is an unusual situation for me. I do run projects as open-opensource but I'm not very experienced in building communities around projects and I've never been approached by someone requesting full access to everything on our first interaction before. 

I trust you, so you're now added to npm as maintainer. As a collaborator to the repository you can do everything to all branches and the only thing you don't have access to is repo settings and delete button. Doesn't sound like a blocker.

I'm committed to maintaining the component for the foreseeable future and I should be responsive on daily basis if you want to communicate about features or PRs. I took some time to respond to this because I needed time to think about your surprising request.

I also added a CONTRIBUTING.md file to openly declare it's an open open source repo.

**Comment by ngokevin** [comment]
Sorry, if you're not comfortable, you don't have to. Just do some small stuff.

I might lift the curation for the Registry and have it be a big list.

**Comment by naugtur** [comment]
I'm perfectly aware I don't have to. But I did, so it's ok afterall.

Curation sounds good. If access to everything except full admin on a repo is enough, I'm ok with that being a requirement. You might need to be more careful when asking ;)

It's probably good for sustainability - you can help listed components get maintainers if someone suddenly drops out. Let's explain this somewhere in a readme maybe?

**Pull request merged**
