### PR TITLE
add gearvr-controls component 

### PR DESCRIPTION
**Pull request by machenmusik**
https://www.npmjs.com/package/aframe-gearvr-controls-component

### CODE REVIEW

**Comment by machenmusik** [comment]
@ngokevin let me know if anything wrong (besides holiday timing)

**Comment by ngokevin** [comment]
OK, just currently working on automating things on github including registry. will look at stuff soon

**Comment by machenmusik** [comment]
No worries, i saw the bump test :-)

**Comment by ngokevin** [comment]
https://github.com/chenzlabs/gearvr-controls/issues/1

**Comment by machenmusik** [comment]
@ngokevin done

**Comment by ngokevin** [comment]
Thanks!

**Pull request merged**
