### PR TITLE
Add aframe-spritesheet-component to registry

### PR DESCRIPTION
**Pull request by OpherV**
Added my component:
https://github.com/EkoLabs/aframe-spritesheet-component

### CODE REVIEW

**Comment by ngokevin** [comment]
Thanks for submitting!

@OpherV @feiss Do you think 2D spritesheets would be commonly useful in 3D/VR applications?

**Comment by OpherV** [comment]
Yes I do. After all, there is no other way to insert pre-baked animations into a 3d scene. 

Common uses :
* gui elements like buttons, headers, progress bars, timers 
* effects like explosions, flares, enhanced lighting sources 
* less resource intensive background items like trees, shrubbery and foliage. the term for this in game dev "billboards", because they always gave you

**Comment by feiss** [comment]
Yeah, this is nice and can be useful, thanks @OpherV !

I although would like to have a way of specify the current image in an absolute fashion. Now there's only a `progress` parameter from 0 to 1. I think the user should be able to specify also an actual index in the spritesheet mode or the key id in the json dictionary.

Great addition, anyway!

**Comment by fernandojsg** [comment]
Just out of curiosity, the sprite is aligned to the original camera position right? not to each one of the per-eye cameras used for stereo render

**Comment by fernandojsg** [comment]
Sorry my fault, I thought it was about a billboard component :)

**Comment by OpherV** [comment]
@feiss sure - I agree that API would be useful as well.

@ngokevin are you considering having this as part of core? If so I can finish implementing @feiss's suggestion and submit a PR

**Comment by ngokevin** [comment]
The Registry is a fine place for this component for now. Let me know when you get @feiss's suggestion down. Thanks!

**Comment by ngokevin** [comment]
Can you add a link to the examples in the Website section in GitHub? https://cloud.githubusercontent.com/assets/674727/24439774/2640bef6-1405-11e7-90d7-c39b4f876ce1.png

**Comment by dmarcos** [comment]
@OpherV we're looking forward to including this in the registry. It's almost ready to go. Do you have some time to bring it back home? Thank you!

**Comment by OpherV** [comment]
@dmarcos yeah! I'll sort things out this week :)

**Comment by OpherV** [comment]
@dmarcos 

I've implemented @feiss's API suggestions

@ngokevin what do you mean by 

> Can you add a link to the examples in the Website section in GitHub?

 Not sure what's this image you've linked 😶

**Comment by ngokevin** [comment]
Sorry for the delay, hope to get back to maintaining the Registry soon.

**Pull request merged**
