### PR TITLE
add stats-in-vr component

### PR DESCRIPTION
**Pull request by machenmusik**
https://www.npmjs.com/package/aframe-stats-in-vr-component

### CODE REVIEW

**Comment by ngokevin** [comment]
Registry:

- Can you add a screenshot to the README for display?

Code Review:

- In `init`, would look cleaner to move the giant timeout to a separate method and then bind.
- In `tick`, can you can use the `time` argument instead of `Date.now()`?
- Do you need to tick/update the stats? Doesn't the stats component handle it?

**Comment by machenmusik** [comment]
per diacussion on aframevr/aframe#2217 I don't currently trust time values from `tick`.

will see what I can do for screenshot

**Comment by machenmusik** [comment]
(is there an example of how the screenshot should be added into the README?)

**Comment by ngokevin** [comment]
Yeah, a lot of the components currently in the Registry just have an image in the README.md. You can upload the image however (e.g., I drag and drop it to a dummy GitHub issue to have GitHub host it).

```
## my-component

foo bar

![myscreenshot](https://cloud.githubusercontent/foofoobar.png)
```

**Comment by machenmusik** [comment]
ok done

**Comment by ngokevin** [comment]
cool. if you want, you can give it a fuzzy version so you can update asynchronously. `0.1.x`. if not, i can merge

**Comment by machenmusik** [comment]
thx for the suggestion

**Comment by ngokevin** [comment]
Cool. Currently working on a GitHub bot to automate the Registry builds.

**Pull request merged**
