### PR TITLE
Add aframe-extras primitives: ocean, grid, tube

### PR DESCRIPTION
**Pull request by donmccurdy**
(I assume that the 'names' field should have both `ocean` and `a-ocean` here?)

### CODE REVIEW

**Comment by ngokevin** [comment]
Sweet, just component names。

**Comment by ngokevin** [comment]
Would it be hard to add images + basic API docs to the READMEs published to npm?

**Comment by donmccurdy** [comment]
Sounds good, i'll fix the component names later today.

How does the README surface? Like for the physics components, which do have a README, the "?" icon is a broken link here: https://aframe.io/docs/0.5.0/components/dynamic-body.html

**Comment by ngokevin** [comment]
Oops, maybe not needed, I think I will update the Registry to be able to specify an image so we don't have to publish to npm.

**Comment by donmccurdy** [comment]
Fixed the `names`. Functionally this is blocked by https://github.com/aframevr/aframe-inspector/pull/463.

**Comment by ngokevin** [comment]
OK, I'll merge and I can now add images from Registry rather than need to have them on npm README.

**Comment by ngokevin** [comment]
Thanks!

**Pull request merged**
